version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    command: [ '--config-file=/config/config.yaml']
    volumes:
      - ./config:/config:ro
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "14269:14269"
      - "4318:4318"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
