receivers:
  otlp:
    protocols:
      grpc:
      http:
        include_metadata: true
        cors_allowed_origins:
        - http://*
        - https://*
        - http://localhost:3036
      allowed_headers:
        - '*'