-- CreateEnum
CREATE TYPE "CONNECTION_STRATEGY" AS ENUM ('DB', 'GOOGLE', 'GITHUB', 'MICROSOFT', 'APPLE');

-- AlterEnum
ALTER TYPE "CONNECTION_TYPE" ADD VALUE 'SOCIAL';

-- AlterTable
ALTER TABLE "connection" ADD COLUMN     "connectionConfig" JSONB,
ADD COLUMN     "strategy" "CONNECTION_STRATEGY" DEFAULT 'DB';
